### ISSUE TITLE
Think what to do

### ISSUE THREAD

**Issue by YukiOnishi1129** [YukiOnishi1129/auto-stock-trading-system#18]
# Sumary
Think what to do

# Objective
make it from where we can make it.

# Tasks

### functions
- [ ] auth
  - [x] login
  - [x] logut
  - [ ] register?
  - [ ] authetication route
- [ ] user
  - [ ] profile
  - [ ] header
- [ ] sidebar

### layouts

- [ ] responsive?

### functions

- [ ] stock trading
  - [ ] purchase
    - [ ] auto?
  - [ ] sell
    - [ ] auto

- [ ] show
  - [ ] stock list
  - [ ] stock detail

- [ ] my stock parameter
  - [ ] my money condition
  - [ ] purchased stock condition
  - [ ] log sold stock list
    - [ ] sold stock detail

- [ ] condition setting
  - [ ] condition of purchase
  - [ ] condition of sold

# Others
