### ISSUE TITLE
feat: Develop connect to db and user tables

### ISSUE THREAD

**Issue by YukiOnishi1129** [YukiOnishi1129/auto-stock-trading-system#6]
# Sumary
Develop connect to db and user tables

# Objective
Develop connect to db and user tables

# Tasks

- [x] create seeding user data at batch-service
- [x] connect user data at user-service
- [x] create grpc relational user at user-service
- [x] create graphql relational user data at bff
- [ ] create graphql relational user data at web-client

# Others
